name: Bug report
description: Report a bug
title: "[BUG]:"
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: textarea
    id: description
    attributes:
      label: Describe what happend
      description: A clear and concise description of what the bug is.
    validations:
      required: true
  - type: textarea
    id: reproduction
    attributes:
      label: Reproduction steps
      description: Give a description of how to reproduce the bug. Please walk through them step by step.
      placeholder: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      description: A clear and concise description of what you expected to happen.
    validations:
      required: true
  - type: textarea
    id: media
    attributes:
      label: Media
      description: If applicable, add screenshots, logs or a video to help explain your problem.
    validations:
      required: false
  - type: input
    id: modpack-version
    attributes:
      label: Modpack Version
      description: The version of Modpack that you are using.
      placeholder: "1.0.1"
    validations:
      required: true
  - type: input
    id: mod-name
    attributes:
      label: Mod Name
      description: The name of the mod that is related to the bug.
    validations:
      required: false
  - type: textarea
    id: additional-information
    attributes:
      label: Additional Information
      description: Any additional information that you would like to share.