
#Visual Settings
[visual]
	#Disables the headache- and possibly seizure-inducing visual effects of Demon's Dream.
	disableDemonsDreamShaders = true

#Misc Settings
[misc]
	#Sync JEI search in storage actuator.
	syncJeiSearch = false

