#gear
<recipetype:tconstruct:casting_table>.removeRecipe(<item:thermal:tin_gear>);
<recipetype:tconstruct:casting_table>.removeRecipe(<item:thermal:iron_gear>);
<recipetype:tconstruct:casting_table>.removeRecipe(<item:thermal:gold_gear>);
<recipetype:tconstruct:casting_table>.removeRecipe(<item:thermal:copper_gear>);
<recipetype:tconstruct:casting_table>.removeRecipe(<item:thermal:lead_gear>);
<recipetype:tconstruct:casting_table>.removeRecipe(<item:thermal:bronze_gear>);
<recipetype:tconstruct:casting_table>.removeRecipe(<item:thermal:electrum_gear>);
<recipetype:tconstruct:casting_table>.removeRecipe(<item:thermal:invar_gear>);
<recipetype:tconstruct:casting_table>.removeRecipe(<item:thermal:constantan_gear>);
<recipetype:tconstruct:casting_table>.removeRecipe(<item:thermal:nickel_gear>);
<recipetype:tconstruct:casting_table>.removeRecipe(<item:thermal:silver_gear>);
<recipetype:tconstruct:casting_table>.removeRecipe(<item:thermal:lumium_gear>);
<recipetype:tconstruct:casting_table>.removeRecipe(<item:thermal:enderium_gear>);
<recipetype:tconstruct:casting_table>.removeRecipe(<item:thermal:signalum_gear>);
#plats
<recipetype:tconstruct:casting_table>.removeRecipe(<item:immersiveengineering:plate_uranium>);
<recipetype:tconstruct:casting_table>.removeRecipe(<item:immersiveengineering:plate_steel>);
<recipetype:tconstruct:casting_table>.removeRecipe(<item:immersiveengineering:plate_electrum>);
<recipetype:tconstruct:casting_table>.removeRecipe(<item:immersiveengineering:plate_constantan>);
<recipetype:tconstruct:casting_table>.removeRecipe(<item:immersiveengineering:plate_nickel>);
<recipetype:tconstruct:casting_table>.removeRecipe(<item:immersiveengineering:plate_silver>);
<recipetype:tconstruct:casting_table>.removeRecipe(<item:immersiveengineering:plate_lead>);
<recipetype:tconstruct:casting_table>.removeRecipe(<item:immersiveengineering:plate_aluminum>);
<recipetype:tconstruct:casting_table>.removeRecipe(<item:thermal:tin_plate>);
<recipetype:tconstruct:casting_table>.removeRecipe(<item:thermal:bronze_plate>);
<recipetype:tconstruct:casting_table>.removeRecipe(<item:thermal:lumium_plate>);
<recipetype:tconstruct:casting_table>.removeRecipe(<item:thermal:signalum_plate>);
<recipetype:tconstruct:casting_table>.removeRecipe(<item:thermal:enderium_plate>);
<recipetype:tconstruct:casting_table>.removeRecipe(<item:thermal:invar_plate>);
<recipetype:tconstruct:casting_table>.removeRecipe(<item:create:brass_sheet>);
<recipetype:tconstruct:casting_table>.removeRecipe(<item:create:copper_sheet>);
<recipetype:tconstruct:casting_table>.removeRecipe(<item:create:golden_sheet>);
<recipetype:tconstruct:casting_table>.removeRecipe(<item:create:iron_sheet>);
<recipetype:tconstruct:casting_table>.removeRecipe(<item:createdeco:netherite_sheet>);
<recipetype:tconstruct:casting_table>.removeRecipe(<item:createdeco:zinc_sheet>);
<recipetype:tconstruct:casting_table>.removeRecipe(<item:createdeco:zinc_sheet>);
<recipetype:tconstruct:casting_table>.removeRecipe(<item:createaddition:zinc_sheet>);

#wires
<recipetype:tconstruct:casting_table>.removeRecipe(<item:immersiveengineering:wire_copper>);
<recipetype:tconstruct:casting_table>.removeRecipe(<item:immersiveengineering:wire_electrum>);
<recipetype:tconstruct:casting_table>.removeRecipe(<item:immersiveengineering:wire_steel>);
<recipetype:tconstruct:casting_table>.removeRecipe(<item:immersiveengineering:wire_aluminum>);
<recipetype:tconstruct:casting_table>.removeRecipe(<item:immersiveengineering:wire_lead>);
<recipetype:tconstruct:casting_table>.removeRecipe(<item:createaddition:gold_wire>);
<recipetype:tconstruct:casting_table>.removeRecipe(<item:createaddition:iron_wire>);

<recipetype:tconstruct:casting_table>.addItemCastingRecipe("bucket", <item:contenttweaker:bucket_cast>, <fluid:tconstruct:molten_iron> * 864, <item:minecraft:bucket>, 200, false, false);
<recipetype:tconstruct:casting_table>.addItemCastingRecipe("bucket-cast", <item:ceramics:unfired_clay_bucket>, <fluid:tconstruct:molten_gold> * 144, <item:contenttweaker:bucket_cast>, 40, true, false);
